name: CI

# run on every push or PR to any branch
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # check out your code
      - uses: actions/checkout@v3

      # set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Lint with Black
        run: poetry run black --check .

      - name: Lint with isort
        run: poetry run isort --check .

      - name: Lint with Flake8
        run: poetry run flake8 . --ignore=E501

      - name: Type check with MyPy
        run: poetry run mypy src/helloworld tests

      - name: Docstring lint (pydocstyle)
        run: poetry run pydocstyle src/helloworld tests

      - name: Run pytest
        run: poetry run pytest

      - name: Security scan with Bandit
        run: poetry run bandit -r src/helloworld -c bandit.yml